const IMG_URL =
  "https://raw.githubusercontent.com/saramff/people-attributes-images/refs/heads/master";

const MEN_BODY_URL = `${IMG_URL}/hombres-experimentales`;
const WOMEN_BODY_URL = `${IMG_URL}/mujeres-experimentales`;
const MEN_FACE_URL = `${IMG_URL}/caras-antiguas-hombres`;
const WOMEN_FACE_URL = `${IMG_URL}/caras-antiguas-mujeres`;

export const menDataArray = [
  {
    bodyImg: `${MEN_BODY_URL}/man-1.jpg`,
    name: "",
    trueSentence: "tiene un vaso de agua.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-2.jpg`,
    faceImg: `${MEN_FACE_URL}/man-2.jpg`,
    name: "",
    trueSentence: "tiene una mochila.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-3.jpg`,
    faceImg: `${MEN_FACE_URL}/man-3.jpg`,
    name: "",
    trueSentence: "tiene unas botas.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-4.jpg`,
    faceImg: `${MEN_FACE_URL}/man-4.jpg`,
    name: "",
    trueSentence: "tiene una maceta.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  }, 
  {
    bodyImg: `${MEN_BODY_URL}/man-5.jpg`,
    faceImg: `${MEN_FACE_URL}/man-5.jpg`,
    name: "",
    trueSentence: "tiene pan.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-6.jpg`,
    faceImg: `${MEN_FACE_URL}/man-6.jpg`,
    name: "",
    trueSentence: "tiene un monopatín.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-7.jpg`,
    faceImg: `${MEN_FACE_URL}/man-7.jpg`,
    name: "",
    trueSentence: "tiene una bandera.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-8.jpg`,
    faceImg: `${MEN_FACE_URL}/man-8.jpg`,
    name: "",
    trueSentence: "tiene una pizza.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-9.jpg`,
    faceImg: `${MEN_FACE_URL}/man-9.jpg`,
    name: "",
    trueSentence: "tiene un albornoz.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-10.jpg`,
    faceImg: `${MEN_FACE_URL}/man-10.jpg`,
    name: "",
    trueSentence: "tiene una silla.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-11.jpg`,
    faceImg: `${MEN_FACE_URL}/man-11.jpg`,
    name: "",
    trueSentence: "tiene un bastón.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-12.jpg`,
    faceImg: `${MEN_FACE_URL}/man-12.jpg`,
    name: "",
    trueSentence: "tiene una linterna.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-13.jpg`,
    faceImg: `${MEN_FACE_URL}/man-13.jpg`,
    name: "",
    trueSentence: "tiene un refresco.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-14.jpg`,
    faceImg: `${MEN_FACE_URL}/man-14.jpg`,
    name: "",
    trueSentence: "tiene una bolsa.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-15.jpg`,
    faceImg: `${MEN_FACE_URL}/man-15.jpg`,
    name: "",
    trueSentence: "tiene un chaleco.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-16.jpg`,
    faceImg: `${MEN_FACE_URL}/man-16.jpg`,
    name: "",
    trueSentence: "tiene un pincel.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-17.jpg`,
    faceImg: `${MEN_FACE_URL}/man-17.jpg`,
    name: "",
    trueSentence: "tiene un plátano.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-18.jpg`,
    faceImg: `${MEN_FACE_URL}/man-18.jpg`,
    name: "",
    trueSentence: "tiene una falda escocesa.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-19.jpg`,
    faceImg: `${MEN_FACE_URL}/man-19.jpg`,
    name: "",
    trueSentence: "tiene una moto.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-20.jpg`,
    faceImg: `${MEN_FACE_URL}/man-20.jpg`,
    name: "",
    trueSentence: "tiene una manzana.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-21.jpg`,
    faceImg: `${MEN_FACE_URL}/man-21.jpg`,
    name: "",
    trueSentence: "tiene una pecera.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-22.jpg`,
    faceImg: `${MEN_FACE_URL}/man-22.jpg`,
    name: "",
    trueSentence: "tiene un trofeo.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-23.jpg`,
    faceImg: `${MEN_FACE_URL}/man-23.jpg`,
    name: "",
    trueSentence: "tiene un peluche.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${MEN_BODY_URL}/man-24.jpg`,
    faceImg: `${MEN_FACE_URL}/man-24.jpg`,
    name: "",
    trueSentence: "tiene un micrófono.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },  
];

export const womenDataArray = [
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-1.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-1.jpg`,
    name: "",
    trueSentence: "tiene un perro.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-2.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-2.jpg`,
    name: "",
    trueSentence: "tiene un helado.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-3.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-3.jpg`,
    name: "",
    trueSentence: "tiene una pelota.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-4.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-4.jpg`,
    name: "",
    trueSentence: "tiene una raqueta.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-5.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-5.jpg`,
    name: "",
    trueSentence: "tiene un ordenador.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-6.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-6.jpg`,
    name: "",
    trueSentence: "tiene un bolso.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-7.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-7.jpg`,
    name: "",
    trueSentence: "tiene una maleta.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-8.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-8.jpg`,
    name: "",
    trueSentence: "tiene una vela.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-9.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-9.jpg`,
    name: "",
    trueSentence: "tiene una galleta.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-10.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-10.jpg`,
    name: "",
    trueSentence: "tiene una botella.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-11.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-11.jpg`,
    name: "",
    trueSentence: "tiene una cámara.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-12.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-12.jpg`,
    name: "",
    trueSentence: "tiene una guitarra.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-13.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-13.jpg`,
    name: "",
    trueSentence: "tiene un libro.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-14.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-14.jpg`,
    name: "",
    trueSentence: "tiene un café.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-15.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-15.jpg`,
    name: "",
    trueSentence: "tiene flores.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-16.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-16.jpg`,
    name: "",
    trueSentence: "tiene un carrito de la compra.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-17.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-17.jpg`,
    name: "",
    trueSentence: "tiene una falda flamenca.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-18.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-18.jpg`,
    name: "",
    trueSentence: "tiene unas llaves.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-19.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-19.jpg`,
    name: "",
    trueSentence: "tiene una cometa.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-20.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-20.jpg`,
    name: "",
    trueSentence: "tiene una cesta.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-21.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-21.jpg`,
    name: "",
    trueSentence: "tiene una caja.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-22.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-22.jpg`,
    name: "",
    trueSentence: "tiene palomitas.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-23.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-23.jpg`,
    name: "",
    trueSentence: "tiene una falda amarilla.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
  {
    bodyImg: `${WOMEN_BODY_URL}/woman-24.jpg`,
    faceImg: `${WOMEN_FACE_URL}/woman-24.jpg`,
    name: "",
    trueSentence: "tiene un periódico.",
    falseSentence: "",
    showFalseSentence: false,
    correct_response: "",
  },
];

// Create name arrays for men and women
export const menNames = [
  "Antonio",
  "José",
  "Manuel",
  "Juan",
  "Francisco",
  "David",
  "Javier",
  "Carlos",
  "Miguel",
  "Jesús",
  "Alejandro",
  "Pedro",
  "Pablo",
  "Ángel",
  "Sergio",
  "Rafa",
  "Andrés",
  "Alberto",
  "Enrique",
  "Rubén",
  "Fernando",
  "Luis",
  "Daniel",
  "Marcos",
];

export const womenNames = [
  "María",
  "Carmen",
  "Ana",
  "Laura",
  "Isabel",
  "Marta",
  "Sara",
  "Elena",
  "Lucía",
  "Patricia",
  "Teresa",
  "Pilar",
  "Silvia",
  "Rosa",
  "Beatriz",
  "Claudia",
  "Raquel",
  "Sonia",
  "Nuria",
  "Alicia",
  "Irene",
  "Andrea",
  "Cristina",
  "Julia",
];

export const falseSentences = [
  "tiene una cerveza.",
  "tiene un coco.",
  "tiene una muñeca.",
  "tiene una báscula.",
  "tiene un sofá.",
  "tiene una manguera.",
  "tiene sushi.",
  "tiene un sándwich.",
  "tiene un cubo.",
  "tiene una flauta.",
  "tiene una bañera.",
  "tiene una hucha.",
  "tiene queso.",
  "tiene un sándwich.",
  "tiene una batidora.",
  "tiene un cepillo.",
  "tiene un martillo.",
  "tiene una sandía.",
  "tiene patatas.",
  "tiene un sándwich.",
  "tiene un ventilador.",
  "tiene un termómetro.",
  "tiene unas cartas.",
  "tiene un cuadro.",
  "tiene una lavadora.",
  "tiene un espejo.",
  "tiene un cenicero.",
  "tiene un cuenco.",
  "tiene una crema.",
  "tiene una moneda.",
  "tiene un jarrón.",
  "tiene una colonia.",
  "tiene una zanahoria.",
  "tiene un teclado.",
  "tiene una ensalada.",
  "tiene sardinas.",
  "tiene un exprimidor.",
  "tiene una regadera.",
  "tiene una pizarra.",
  "tiene una cebolla.",
  "tiene un secador.",
  "tiene una bicicleta.",
  "tiene una escalera.",
  "tiene miel.",
  "tiene un cuadro.",
  "tiene unos prismáticos.",
  "tiene brócoli.",
  "tiene una mariposa.",
]
